### ISSUE TITLE
broken_axis support?

### ISSUE THREAD

**Issue by farleylai** [eseifert/gral#140] opened 2016-06-10 07:27 UTC
GRAL in many aspects are better than JFreeChart but it seem like there is a missing piece about the broken axis as provided by matplotlib which is quite essential for scientific dataset visualizations.

![image](https://cloud.githubusercontent.com/assets/158540/15957155/c755cbbc-2eb2-11e6-946d-aeba290b7786.png)

Alternatively, it can be done in some way already supported by GRAL?

**Comment by eseifert** [comment] 2016-06-13 09:03
Great to see that you like GRAL!

However, I am afraid that breaks in the axes are currently not supported. The idea of including this has been around for quite some time, though (see issue #10). Right now, there is some infrastructure work going on in GRAL and we want to finish it first to get a stable API and release v1.0. @seifertm and I will take a look on how to prioritize this feature.

I will close this issue as a duplicate of #10.

**Closed by eseifert** 2016-06-13 09:03 UTC
Labels: duplicate

**Comment by farleylai** [comment] 2016-06-20 00:08
I appreciate your great effort and also think GRAL is designed well. Just in my experience so far, JVM languages don't seem to have a full-fledged plot toolkit for publication use. Whenever going deeper, there are always potential/unknown limitations despite the fact that matplotlib is a bit old. I recently need to draw boxplots where the difference between min and max is very large (~5000) but the min, medium, q1 and q3 are very close (<10). This could be the case the broken axis comes in handy. It seems like this feature may be implemented using stack plots. Merely wondering.
