### ISSUE TITLE
InteractivePanel loses zoom after repaint

### ISSUE THREAD

**Issue by eseifert** [eseifert/gral#100] opened 2015-03-30 10:32 UTC
In my case I added dynamically DataSource and need to repaint the panel, but Panel loses zoom.

 _Imported from trac ticket #101,  created by gabber on 02-05-2014 at 23:13, last modified: 02-10-2014 at 10:27_

**Comment by eseifert** [comment] 2015-03-30 10:32
Thanks for the report. This may be related to automatic scaling of axes which is active by default. Adding new data sources will set new axis ranges and reset zooming.

A possible solution would be to disable automatic scaling on all axes with `Axis.setAutoscale()` and to manually call `Plot.autoscaleAxis()` when necessary.

I will leave the ticket open until I have time to look at the issue.

_Trac comment by eseifert on 02-08-2014 at 11:19_

**Comment by eseifert** [comment] 2015-03-30 10:32
Thanks alot for fast replay, disabling autoscale on both Axis helped :)

_Trac comment by gabber on 02-10-2014 at 10:27_

**Comment by seifertm** [comment] 2015-04-08 09:13
Closing this issue, because automatic scaling of axes is the default and expected behaviour.

**Closed by seifertm** 2015-04-08 09:13 UTC
Labels: wontfix
